site:
  name: NARVIS
  hosts:
    - cn01:
        hostname: 192.168.2.30
        port: 8889
        type: CaptureNode
    - cn02:
        hostname: 192.168.2.31
        port: 8889
        type: CaptureNode
    - cn03:
        hostname: 192.168.2.32
        port: 8889
        type: CaptureNode
    - cn04:
        hostname: 192.168.2.33
        port: 8889
        type: CaptureNode